# Generated by Django 5.2 on 2025-04-20 21:21

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('armor', models.CharField(verbose_name=django.db.models.fields.IntegerField)),
                ('fire_res', models.CharField(verbose_name=django.db.models.fields.IntegerField)),
                ('cold_res', models.CharField(verbose_name=django.db.models.fields.IntegerField)),
                ('lighting_res', models.CharField(verbose_name=django.db.models.fields.IntegerField)),
                ('chaos_res', models.CharField(verbose_name=django.db.models.fields.IntegerField)),
            ],
        ),
    ]
