# Generated by Django 5.2 on 2025-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb_database_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='races',
            options={'verbose_name': 'Расу', 'verbose_name_plural': 'Расы'},
        ),
        migrations.AlterField(
            model_name='races',
            name='armor',
            field=models.IntegerField(default=0, verbose_name='Броня'),
        ),
        migrations.AlterField(
            model_name='races',
            name='chaos_res',
            field=models.IntegerField(default=0, verbose_name='Резист к хаосу'),
        ),
        migrations.AlterField(
            model_name='races',
            name='cold_res',
            field=models.IntegerField(default=0, verbose_name='Резист к холоду'),
        ),
        migrations.AlterField(
            model_name='races',
            name='fire_res',
            field=models.IntegerField(default=0, verbose_name='Резист к огню'),
        ),
        migrations.AlterField(
            model_name='races',
            name='lighting_res',
            field=models.IntegerField(default=0, verbose_name='Резист к молнии'),
        ),
        migrations.AlterField(
            model_name='races',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название расы'),
        ),
    ]
