# Generated by Django 5.2 on 2025-04-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb_database_app', '0003_innateabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название камня силы')),
                ('text', models.TextField(verbose_name='Описание камня силы')),
                ('stone_type', models.CharField(verbose_name='Тип камня силы')),
            ],
            options={
                'verbose_name': 'Камень силы',
                'verbose_name_plural': 'Камни силы',
            },
        ),
        migrations.AlterModelOptions(
            name='innateabilities',
            options={'verbose_name': 'Способность', 'verbose_name_plural': 'Способностей'},
        ),
    ]
