# Generated by Django 5.2 on 2025-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb_database_app', '0004_stones_alter_innateabilities_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя бога')),
                ('divine_gift', models.CharField(verbose_name='Божественный дар')),
                ('bless', models.CharField(verbose_name='Благословение')),
                ('amulet', models.CharField(verbose_name='Амулет аэдра')),
                ('backpack_with_amulet', models.CharField(verbose_name='Рюкзак с амулетом аэдра')),
            ],
            options={
                'verbose_name': 'Аэдра',
            },
        ),
    ]
