# Generated by Django 5.2 on 2025-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb_database_app', '0005_aedra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя бога')),
                ('divine_gift', models.CharField(verbose_name='Божественный дар')),
                ('artefact', models.CharField(verbose_name='Артефакт')),
                ('effect', models.CharField(verbose_name='Благословение')),
            ],
            options={
                'verbose_name': 'Даэдра',
            },
        ),
    ]
